package com.jjw.easygallery.feature.autotag

import com.jjw.easygallery.R

/**
 * ML Kit 기본 모델의 영어 라벨을 한국어로 보여준다(`docs/AUTO_TAGGING.md` §6).
 *
 * 목록은 **실기기에서 사진 5687장을 분석해 나온 실제 빈도**(236가지) 상위부터 채웠다.
 * 짐작으로 고르면 자주 나오는 라벨(Leisure·Cuisine·Tableware 등)이 영어로 남는다.
 * 표에 없는 라벨은 **영어 원문 그대로** 둔다 — 모델이 새 라벨을 내도 화면이 비지 않는다.
 */
internal object AutoTagLabels {

    fun displayNameRes(label: String): Int? = KOREAN[label]

    private val KOREAN: Map<String, Int> = mapOf(
        "Leisure" to R.string.auto_tag_label_leisure,
        "Food" to R.string.auto_tag_label_food,
        "Cuisine" to R.string.auto_tag_label_cuisine,
        "Jeans" to R.string.auto_tag_label_jeans,
        "Flower" to R.string.auto_tag_label_flower,
        "Sky" to R.string.auto_tag_label_sky,
        "Plant" to R.string.auto_tag_label_plant,
        "Building" to R.string.auto_tag_label_building,
        "Tableware" to R.string.auto_tag_label_tableware,
        "Dog" to R.string.auto_tag_label_dog,
        "Fun" to R.string.auto_tag_label_fun,
        "Screenshot" to R.string.auto_tag_label_screenshot,
        "Paper" to R.string.auto_tag_label_paper,
        "Room" to R.string.auto_tag_label_room,
        "Meal" to R.string.auto_tag_label_meal,
        "Vacation" to R.string.auto_tag_label_vacation,
        "Road" to R.string.auto_tag_label_road,
        "Vehicle" to R.string.auto_tag_label_vehicle,
        "Jacket" to R.string.auto_tag_label_jacket,
        "Metal" to R.string.auto_tag_label_metal,
        "Chair" to R.string.auto_tag_label_chair,
        "Branch" to R.string.auto_tag_label_branch,
        "Pet" to R.string.auto_tag_label_pet,
        "Textile" to R.string.auto_tag_label_textile,
        "Sitting" to R.string.auto_tag_label_sitting,
        "Toy" to R.string.auto_tag_label_toy,
        "Cat" to R.string.auto_tag_label_cat,
        "Asphalt" to R.string.auto_tag_label_asphalt,
        "Skyscraper" to R.string.auto_tag_label_skyscraper,
        "Standing" to R.string.auto_tag_label_standing,
        "Forest" to R.string.auto_tag_label_forest,
        "Smile" to R.string.auto_tag_label_smile,
        "Space" to R.string.auto_tag_label_space,
        "Jungle" to R.string.auto_tag_label_jungle,
        "Poster" to R.string.auto_tag_label_poster,
        "Fur" to R.string.auto_tag_label_fur,
        "Wheel" to R.string.auto_tag_label_wheel,
        "Event" to R.string.auto_tag_label_event,
        "Wall" to R.string.auto_tag_label_wall,
        "Cool" to R.string.auto_tag_label_cool,
        "Fast food" to R.string.auto_tag_label_fast_food,
        "Car" to R.string.auto_tag_label_car,
        "Hand" to R.string.auto_tag_label_hand,
        "Outerwear" to R.string.auto_tag_label_outerwear,
        "Product" to R.string.auto_tag_label_product,
        "Pattern" to R.string.auto_tag_label_pattern,
        "Desk" to R.string.auto_tag_label_desk,
        "Nail" to R.string.auto_tag_label_nail,
        "Skyline" to R.string.auto_tag_label_skyline,
        "River" to R.string.auto_tag_label_river,
        "Infrastructure" to R.string.auto_tag_label_infrastructure,
        "Mobile phone" to R.string.auto_tag_label_mobile_phone,
        "Shoe" to R.string.auto_tag_label_shoe,
        "Tower" to R.string.auto_tag_label_tower,
        "Hat" to R.string.auto_tag_label_hat,
        "Rock" to R.string.auto_tag_label_rock,
        "Umbrella" to R.string.auto_tag_label_umbrella,
        "Beach" to R.string.auto_tag_label_beach,
        "Denim" to R.string.auto_tag_label_denim,
        "Web page" to R.string.auto_tag_label_web_page,
        "Vegetable" to R.string.auto_tag_label_vegetable,
        "Roof" to R.string.auto_tag_label_roof,
        "Petal" to R.string.auto_tag_label_petal,
        "Lake" to R.string.auto_tag_label_lake,
        "Soil" to R.string.auto_tag_label_soil,
        "Glasses" to R.string.auto_tag_label_glasses,
        "Crowd" to R.string.auto_tag_label_crowd,
        "Musical instrument" to R.string.auto_tag_label_musical_instrument,
        "Bumper" to R.string.auto_tag_label_bumper,
        "Bird" to R.string.auto_tag_label_bird,
        "Temple" to R.string.auto_tag_label_temple,
        "Bridge" to R.string.auto_tag_label_bridge,
        "Pillow" to R.string.auto_tag_label_pillow,
        "Shorts" to R.string.auto_tag_label_shorts,
        "Ear" to R.string.auto_tag_label_ear,
        "Skin" to R.string.auto_tag_label_skin,
        "Eyelash" to R.string.auto_tag_label_eyelash,
        "Field" to R.string.auto_tag_label_field,
        "Couch" to R.string.auto_tag_label_couch,
        "Mountain" to R.string.auto_tag_label_mountain,
        "Selfie" to R.string.auto_tag_label_selfie,
        "Garden" to R.string.auto_tag_label_garden,
        "Tire" to R.string.auto_tag_label_tire,
        "Cookware and bakeware" to R.string.auto_tag_label_cookware,
        "Bread" to R.string.auto_tag_label_bread,
        "Hair" to R.string.auto_tag_label_hair,
        "Stuffed toy" to R.string.auto_tag_label_stuffed_toy,
        "Flowerpot" to R.string.auto_tag_label_flowerpot,
        "Bench" to R.string.auto_tag_label_bench,
        "Boat" to R.string.auto_tag_label_boat,
        "Whiteboard" to R.string.auto_tag_label_whiteboard,
        "Windshield" to R.string.auto_tag_label_windshield,
        "Wool" to R.string.auto_tag_label_wool,
        "Cutlery" to R.string.auto_tag_label_cutlery,
        "Lunch" to R.string.auto_tag_label_lunch,
        "Monochrome" to R.string.auto_tag_label_monochrome,
        "Sand" to R.string.auto_tag_label_sand,
        "Cup" to R.string.auto_tag_label_cup,
        "Flesh" to R.string.auto_tag_label_flesh,
        "Porcelain" to R.string.auto_tag_label_porcelain,
        "Prairie" to R.string.auto_tag_label_prairie,
        "Trunk" to R.string.auto_tag_label_trunk,
        "Bedroom" to R.string.auto_tag_label_bedroom,
        "Shelf" to R.string.auto_tag_label_shelf,
        "Sunglasses" to R.string.auto_tag_label_sunglasses,
        "Bag" to R.string.auto_tag_label_bag,
        "Aviation" to R.string.auto_tag_label_aviation,
        "Aircraft" to R.string.auto_tag_label_aircraft,
        "Brick" to R.string.auto_tag_label_brick,
        "Aerospace engineering" to R.string.auto_tag_label_aerospace,
        "Plush" to R.string.auto_tag_label_plush,
        "Coffee" to R.string.auto_tag_label_coffee,
        "Dress" to R.string.auto_tag_label_dress,
        "Countertop" to R.string.auto_tag_label_countertop,
        "Stairs" to R.string.auto_tag_label_stairs,
        "Tile" to R.string.auto_tag_label_tile,
        "Wine" to R.string.auto_tag_label_wine,
        "Muscle" to R.string.auto_tag_label_muscle,
        "Alcohol" to R.string.auto_tag_label_alcohol,
        "Cake" to R.string.auto_tag_label_cake,
        "Dessert" to R.string.auto_tag_label_dessert,
        "Drink" to R.string.auto_tag_label_drink,
        "Tree" to R.string.auto_tag_label_tree,
        "Cloud" to R.string.auto_tag_label_cloud,
        "Sunset" to R.string.auto_tag_label_sunset,
        "Snow" to R.string.auto_tag_label_snow,
        "Water" to R.string.auto_tag_label_water,
        "Street" to R.string.auto_tag_label_street,
        "Bicycle" to R.string.auto_tag_label_bicycle,
        "Person" to R.string.auto_tag_label_person,
        "Text" to R.string.auto_tag_label_text,
        "Document" to R.string.auto_tag_label_document,
        "Book" to R.string.auto_tag_label_book,
        "Furniture" to R.string.auto_tag_label_furniture,
        "Table" to R.string.auto_tag_label_table,
        "Art" to R.string.auto_tag_label_art,
        "Night" to R.string.auto_tag_label_night,
        "Concert" to R.string.auto_tag_label_concert,
        "Sports" to R.string.auto_tag_label_sports,
        "Fireworks" to R.string.auto_tag_label_fireworks,
    )
}
